name: keycloak_flutter
description: Keycloak client adapter for flutter based on the keycloak-js implementation.
version: 0.1.0
homepage: https://github.com/gibahjoe/keycloak_flutter

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
